name: ğŸ”¨ Build

on:
  workflow_call:

jobs:
  build_server:
    name: "server"
    runs-on: methylphenidate-runner-set
    timeout-minutes: 80
    permissions:
      contents: read
      packages: write
      deployments: write
      id-token: write
    steps:
      - name: ğŸ“œ Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: âœ³ï¸ Setup OS
        uses: "./.github/actions/setup-os"

      - name: âœ³ï¸ Setup Node.js
        uses: "./.github/actions/setup-node"

      - name: âœ³ï¸ Build server
        id: build-node-server
        run: pnpm run build
        shell: bash

      - name: ğŸ“¦ Build Archive of Artifacts
        run: |
          zip -r server-build-artifacts.zip apps/server/dist apps/server/public

      - name: ğŸ“¦ Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: server-build-artifacts
          path: server-build-artifacts.zip