name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - next
  push:
    branches:
      - next
      - main
    paths:
      - 'package.json'
      - 'yarn.lock'
      - 'apps/server/**'
      - 'packages/**'
      - 'libs/shared/**'
env:
  TF_WORKSPACE: keinsell-dev

jobs:
  # Pre-build is a quality-control step, dedicated for checking code formatting,
  # catching linting issues and other common dev-level mistakes.
  pre-build:
    name: ğŸ’¡ Pre-build
    uses: ./.github/workflows/pre-build.yml


  # Build is a step dedicated for building application.
  build:
    name: ğŸ”¨ Build
    uses: ./.github/workflows/build.yml
    secrets: inherit

  # Testing is a step dedicated for running all tests associated with given app.
  testing:
    runs-on: methylphenidate-runner-set
    name: ğŸ”¬ Testing
    needs: [ "build" ]
    steps:
      - name: ğŸ“œ Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: âœ³ï¸ Setup Node.js
        uses: "./.github/actions/setup-node"

  cleanup:
    name: ğŸ§¼ Cleanup
    uses: ./.github/workflows/cleanup.yml
    secrets: inherit