name: Continuous Integration

on:
  pull_request:
    branches:
      - main
      - next
  push:
    branches:
      - next
      - main
    paths:
      - 'package.json'
      - 'yarn.lock'
      - 'apps/server/**'
      - 'packages/**'
      - 'libs/shared/**'
env:
  TF_WORKSPACE: keinsell-dev
  CONFIGU_ORG: ${{ secrets.CONFIGU_ORG }}
  CONFIGU_SECRET: ${{ secrets.CONFIGU_SECRET }}

jobs:
  # Pre-build is a quality-control step, dedicated for checking code formatting,
  # catching linting issues and other common dev-level mistakes.
  pre-build:
    name: üí° Pre-build
    runs-on: methylphenidate-runner-set
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ‚ú≥Ô∏è Setup Node.js
        uses: "./.github/actions/setup-node"


  # Build is a step dedicated for building application.
  build:
    name: üî® Build
    runs-on: methylphenidate-runner-set
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ‚ú≥Ô∏è Setup Node.js
        uses: "./.github/actions/setup-node"

  # Testing is a step dedicated for running all tests associated with given app.
  testing:
    runs-on: methylphenidate-runner-set
    name: üî¨ Testing
    needs: [ "build" ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: ‚ú≥Ô∏è Setup Node.js
        uses: "./.github/actions/setup-node"